<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-22T14:36:18 PKT" name="Default suite" finished-at="2025-04-22T14:36:38 PKT" duration-ms="20458">
    <groups>
    </groups>
    <test started-at="2025-04-22T14:36:18 PKT" name="Default test" finished-at="2025-04-22T14:36:38 PKT" duration-ms="20458">
      <class name="tests.LoginPageTests">
        <test-method is-config="true" signature="SetupReport()[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:17 PKT" name="SetupReport" finished-at="2025-04-22T14:36:18 PKT" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetupReport -->
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:18 PKT" name="setup" finished-at="2025-04-22T14:36:25 PKT" duration-ms="6914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:25 PKT" name="ValidLoginTest" data-provider="LoginData2" finished-at="2025-04-22T14:36:25 PKT" duration-ms="319" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Just a moment...] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.LoginPageTests.ValidLoginTest(LoginPageTests.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLoginTest -->
        <test-method is-config="true" signature="Clean(org.testng.ITestResult)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:25 PKT" name="Clean" finished-at="2025-04-22T14:36:25 PKT" duration-ms="556" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidLoginTest status=FAILURE method=LoginPageTests.ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:25 PKT" name="setup" finished-at="2025-04-22T14:36:29 PKT" duration-ms="3748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:29 PKT" name="ValidLoginTest" data-provider="LoginData2" finished-at="2025-04-22T14:36:29 PKT" duration-ms="241" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Just a moment...] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.LoginPageTests.ValidLoginTest(LoginPageTests.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLoginTest -->
        <test-method is-config="true" signature="Clean(org.testng.ITestResult)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:29 PKT" name="Clean" finished-at="2025-04-22T14:36:30 PKT" duration-ms="591" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidLoginTest status=FAILURE method=LoginPageTests.ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:30 PKT" name="setup" finished-at="2025-04-22T14:36:34 PKT" duration-ms="3693" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:34 PKT" name="ValidLoginTest" data-provider="LoginData2" finished-at="2025-04-22T14:36:38 PKT" duration-ms="4008" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin@yourstore.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Just a moment...] but found [Dashboard / nopCommerce administration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [Dashboard / nopCommerce administration]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.LoginPageTests.ValidLoginTest(LoginPageTests.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLoginTest -->
        <test-method is-config="true" signature="Clean(org.testng.ITestResult)[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:38 PKT" name="Clean" finished-at="2025-04-22T14:36:38 PKT" duration-ms="346" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidLoginTest status=FAILURE method=LoginPageTests.ValidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTests@6f10d5b6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Clean -->
        <test-method is-config="true" signature="FlushReport()[pri:0, instance:tests.LoginPageTests@6f10d5b6]" started-at="2025-04-22T14:36:38 PKT" name="FlushReport" finished-at="2025-04-22T14:36:42 PKT" duration-ms="3577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlushReport -->
      </class> <!-- tests.LoginPageTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
